title: "UCSB-SBHS-CS"
github_url: https://github.com/ucsb-sbhs-cs/ucsb-sbhs-cs.github.io

exclude: ['vendor', 'setup.sh', 'jekyll.sh']

timezone: America/Los_Angeles

collections:

  dsw:
    exclude: "index.md"
    output: true
    permalink: /dsw/:path/

  topics:
    output: true
    permalink: /topics/:path/

  assignments:
    output: true
    permalink: /assignments/:path/

  lessons:
    output: true
    permalink: /lessons/:path/

  resources:
    output: true
    permalink: /resources/:path/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

  - scope:
      path: ""
      type: topics
    values:
      layout: topic

  - scope:
      path: ""
      type: dsw
    values:
      layout: curriculum

  - scope:
      path: ""
      type: resources
    values:
      layout: topic

  - scope:
      path: ""
      type: lessons
    values:
      layout: topic

  - scope:
      path: ""
      type: assignments
    values:
      layout: assignment



